//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace uspto.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uspto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 license.cert 的本地化字符串。
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BwIAAACkAABSU0EyAAgAAAEAAQD5vRdpOq1FhHkBWWPSAM8lHIUNhmY77ATgDq7AHiGl+XTdWqFssaNrZkltYqhi7ed0dJ0uGKWKy5l4oOu+9n8eXRTwWrBJvlWZyTKmLj1WmIPsjjR6jqn7w54dV7QrhML7NsHhgsCLLAWj+AT4KeMpsgNM6NvvmalP145AfgknD7mF5zvs+x4IHh85UY//fUdz8+jq80ab8LUnswaB59bf2OYgrq7sduk8fP38E+ixVNgmBN+AG3TAmHz8F+rTdakyEnAiMmHeOGNbata7v03tvem5o89XOWUi8vHozKTmiF/2YKVW9Q1tdhp+AOGMnMUgbG+7d5b5xXJbbUGEEhS0SxtGmcsNn7ElR9y2cC3o1d+IIOSDinVieqt2IcPpbaS0hlOdbTxUc2q2NEV9NCS3frd0f5K8pLSqv2dW60XNtTEeg55H+YnJN89aX5O5VUjILngr6x65z9lSJEsdWn99vjfJFt7XWce6PjS5 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string pk {
            get {
                return ResourceManager.GetString("pk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BgIAAACkAABSU0ExAAgAAAEAAQD5vRdpOq1FhHkBWWPSAM8lHIUNhmY77ATgDq7AHiGl+XTdWqFssaNrZkltYqhi7ed0dJ0uGKWKy5l4oOu+9n8eXRTwWrBJvlWZyTKmLj1WmIPsjjR6jqn7w54dV7QrhML7NsHhgsCLLAWj+AT4KeMpsgNM6NvvmalP145AfgknD7mF5zvs+x4IHh85UY//fUdz8+jq80ab8LUnswaB59bf2OYgrq7sduk8fP38E+ixVNgmBN+AG3TAmHz8F+rTdakyEnAiMmHeOGNbata7v03tvem5o89XOWUi8vHozKTmiF/2YKVW9Q1tdhp+AOGMnMUgbG+7d5b5xXJbbUGEEhS0 的本地化字符串。
        /// </summary>
        internal static string pub {
            get {
                return ResourceManager.GetString("pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 userid.conf 的本地化字符串。
        /// </summary>
        internal static string userid {
            get {
                return ResourceManager.GetString("userid", resourceCulture);
            }
        }
    }
}
